Issue/6
saya-minm/lamp_practice pull request #7
Opened 2019-10-19 00:53 UTC by saya-minm

ｈ関数を全て追加しました

2019-10-19 13:08 UTC, thisprodigiousgeek requested changes
着実に作業が進んでいらっしゃいますね！
まだpushされたブランチでは
header.php
header_logined.php
login_view.php
については変更が行われていないようですが、これらのファイルはいかがでしょうか？
コミットから漏れている(addし忘れ）かもしれないのでgit statusで確認してみてくださいね！

2019-10-20 08:19 UTC, saya-minm commented
addし忘れておりました！申し訳ありません。
今add、commit、pushしました。お手数ですが再度ご確認をお願いいたします。

2019-10-20 22:25 UTC, thisprodigiousgeek requested changes
しっかりステージングしていただけましたね！
あとは、admin_view.phpのスタイルシート読み込みの箇所で1箇所エスケープ漏れがあるようです。
こちらが出来上がれば完成ですので、最後の仕上げ頑張っていきましょう！

2019-10-20 22:45 UTC, saya-minm commented
何度も申し訳ありません。admin_view.phpの漏れていた箇所にh関数を追加いたしました。
よろしくお願いいたします！

2019-10-20 22:47 UTC, thisprodigiousgeek approved these changes
はい、こちらでバッチリですね！マージさせていただきます！

2019-10-20 22:47 UTC, merged